'''
Project_2 phase 5
Queue to store the tasks generated by the game
'''
from array204 import *
class Queue:
    '''
    Queue implemented with a circular array, code from in class hand out, Professor Dancy
    '''
    def __init__(self, max_size):
        self._count = 0
        self._front = 0
        self._back = max_size-1
        self._q_array = Array( max_size )

    def is_empty(self):
        return self._count == 0

    def is_full(self):
        return self._count == len(self._q_array)

    def __len__(self):
        return self._count

    def enqueue(self, item):
        assert not self.is_full()
        max_size = len(self._q_array)
        self._back = (self._back + 1) % max_size
        self._q_array[self._back] = item
        self._count += 1

    def dequeue(self):
        assert not self.is_empty()
        item = self._q_array[ self._front ]
        max_size = len(self._q_array)
        self._front = (self._front + 1) % max_size
        self._count -= 1
        return item

    def peek(self):
        return self._q_array[ self._front ]
