#include <iostream>
#include <string>
using namespace std;

#include "friend.h"
// DO NOT EDIT THIS FILE
int main() {
    RodeoClown * bob = new RodeoClown();
    bob->laugh();
    bob->gallop();

    // normal people cannot make bob dance because dance is private
    // bob->dance();  

    // The bull can make bob dance
    Bull * bull = new Bull();
    Spectators * people = new Spectators();
    bull->charge(bob);
    people->applaude(bull);
    bull->charge(bob);
}

